# Generated by Django 5.2.2 on 2025-07-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_produto", models.CharField(max_length=5)),
                ("nome", models.CharField(max_length=200)),
                ("categoria", models.CharField(max_length=50)),
                ("estoque_atual", models.IntegerField()),
                ("estoque_minimo", models.IntegerField()),
            ],
        ),
    ]
